//lista de productos
const productos = [
  {
    id: "1",
    productName: "Aceite BiOlive 500ml",
    price: 875,
    quanty: 1,
    img: "./media/biolive.jpg",
  },
  {
    id: "2",
    productName: "Aceite Laur 500ml",
    price: 1300,
    quanty: 1,
    img: "./media/laur.jpg",
  },
  {
    id: "3",
    productName: "Aceite Wangler 500ml",
    price: 1900,
    quanty: 1,
    img: "./media/wangler.jpg",
    category: "botella3",
  },

  {
    id: "4",
    productName: "Aceitunas Mendoza",
    price: 750,
    quanty: 1,
    img: "./media/aceitunas.jpg",
    category: "botella1,"
  },

  {
    id: "5",
    productName: "Pasta de Oliva",
    price: 590,
    quanty: 1,
    img: "./media/lecumberri.jpg",
    category: "botella3",
  },

  {
    id: "6",
    productName: "Aceite Olivares 500ml",
    price: 520,
    quanty: 1,
    img: "./media/olivares.jpg",
    category: "botella3",
  },
  {
    id: "7",
    productName: "Aceite Momentos 500ml",
    price: 3080,
    quanty: 1,
    img: "./media/momentos.jpg",
    category: "botella2",
  },
  {
    id: "8",
    productName: "Aceite Quinta 500ml",
    price: 2500,
    quanty: 1,
    img: "./media/quintag.jpg",
    category: "botella1",
  },

  {
    id: "9",
    productName: "Aceite Doña Juana 500ml",
    price: 900,
    quanty: 1,
    img: "./media/doñajuana.jpg",
  },
  {
    id: "10",
    productName: "Aceite de Oliva en Aerosol",
    price: 1300,
    quanty: 1,
    img: "./media/aerosol.jpg",
  },
  {
    id: "11",
    productName: "Aceite Marchenica 2 lt",
    price: 2500,
    quanty: 1,
    img: "./media/marchenica.jpg",
  },
  {
    id: "12",
    productName: "Aceitunas Ahumadas",
    price: 1800,
    quanty: 1,
    img: "./media/aceitunas_ahumadas.jpg",
  },
  {
    id: "13",
    productName: "Aceitunas Verdes",
    price: 1200,
    quanty: 1,
    img: "./media/frutolivo.jpg",
  },
  {
    id: "14",
    productName: "Aceitunas Negras 130 g",
    price: 1300,
    quanty: 1,
    img: "./media/olisac.jpg",
  },
  {
    id: "15",
    productName: "Pasta de Aceitunas 170 g",
    price: 1200,
    quanty: 1,
    img: "./media/pasta.jpg",
  },
  {
    id: "16",
    productName: "Pasta de Aceitunas 170 g",
    price: 1300,
    quanty: 1,
    img: "./media/vanoli.jpg",
  },
  {
    id: "17",
    productName: "Aceitunas Descarozadas 160 g",
    price: 1800,
    quanty: 1,
    img: "./media/vanoli_desc.jpg",
  },
  {
    id: "18",
    productName: "Aceitunas Descarozadas 350 g",
    price: 2300,
    quanty: 1,
    img: "./media/vistalarga.jpg",
  },
  {
    id: "19",
    productName: "Aceitunas Descarozadas 350 g",
    price: 2400,
    quanty: 1,
    img: "./media/terramia.jpg",
  },
  {
    id: "20",
    productName: "Pasta de Aceitunas 235 g",
    price: 2000,
    quanty: 1,
    img: "./media/pastan.jpg",
  },
];

